version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongoreservationdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/reservationManagementDb

volumes:
  mongo-data:
